import React from 'react'
import Head from 'next/head'
import Layout from '../components/layout'
import { DATABASE_ID, TOKEN } from "../config";
import Projects from '../components/projects/projects';

export default function projects({projects}) {

  return (
    <>    
        <Layout>
            <Head>
            <title>Jin Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className="py-3 pl-6 md:text-3xl sm:text-2xl font-bold">Total Project: {projects.results.length}</h1>
            <div className="project grid md:grid-cols-3 sm:w-full">
                {projects.results.map((project) => (
                    <Projects
                        key={project.id}
                        project={project}
                    />
                ))}
            </div>
        </Layout>
    </>
  )
}


export async function getStaticProps() {

    const options = {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Notion-Version': '2022-02-22',
          'Content-Type': 'application/json',
          Authorization: `Bearer ${TOKEN}`
        },
        body: JSON.stringify({page_size: 100, sorts: [
            {
                "property": "Name",
                "direction": "ascending"
            }
        ]})
      };
    const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options)
    const projects = await res.json()
    return {
      props: {projects},
    }
  }